FROM maven:3.9.5-eclipse-temurin-21-alpine AS build

WORKDIR /project

COPY . .

RUN mvn clean package -DskipTests


FROM eclipse-temurin:21-jre-alpine

RUN addgroup --system spring && adduser --system spring --ingroup spring

COPY --from=build /project/target/*.jar app.jar

USER spring:spring

ENTRYPOINT ["java","-jar","/app.jar"]
