FROM mcr.microsoft.com/dotnet/sdk:8.0-jammy AS build

WORKDIR /source

COPY *.csproj .
RUN dotnet restore

COPY . .

RUN dotnet publish -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0-jammy-chiseled

WORKDIR /app

COPY --from=build /app .

USER 1000

ENTRYPOINT ["./dotnetapp"]
