FROM golang:1.22-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /myapp

FROM scratch

COPY --from=build /myapp /myapp

USER 10000

EXPOSE 8080

CMD ["/myapp"]