FROM python:3.12-slim AS build

WORKDIR /usr/app

RUN python -m venv /usr/app/venv
ENV PATH="/usr/app/venv/bin:$PATH"

COPY requirements.txt .
RUN pip install -r requirements.txt

FROM python:3.12-slim

RUN groupadd -g 10000 python && \
    useradd -r -u 10000 -g python python

WORKDIR /usr/app/venv
COPY --from=build /usr/app/venv ./venv

COPY app.py .

USER 10000

ENV PATH="/usr/app/venv/bin:$PATH"
CMD ["python", "app.py"]
