FROM python:3.12-slim

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN groupadd -g 10000 python && \
    useradd -r -u 10000 -g python python

RUN mkdir /app && chown python:python /app
WORKDIR /app

COPY app.py .

USER 10000

CMD ["python", "app.py"]
